#!/usr/bin/env python3
"""Build data/uganda-geo.json: SVG path data for Uganda, its districts and its lakes.

Source: Natural Earth 10m cultural + physical vectors (public domain).
Run from the repo root:  python3 tools/fetch_geo.py
"""
import json, math, os, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, ".cache")
BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson"
LAYERS = ["ne_10m_admin_0_countries", "ne_10m_admin_1_states_provinces", "ne_10m_lakes"]
LAKES = ("Lake Victoria", "Lake Albert", "Lake Kyoga", "Lake Kwania", "Lake Edward", "Lake George")

# national map: 1000pt wide, height follows the country's true aspect ratio
NAT_W, NAT_PAD = 1000.0, 8.0
# Greater Kampala inset: fixed geographic window, 320pt wide
INSET_BOX = (32.20, 0.10, 32.88, 0.55)  # lon0, lat0, lon1, lat1
INSET_W = 320.0


def load(layer):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, layer + ".geojson")
    if not os.path.exists(path):
        print("downloading", layer)
        urllib.request.urlretrieve(f"{BASE}/{layer}.geojson", path)
    with open(path) as fh:
        return json.load(fh)


def polys(geom):
    return [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]


def bbox(geom):
    xs = [c[0] for p in polys(geom) for c in p[0]]
    ys = [c[1] for p in polys(geom) for c in p[0]]
    return min(xs), min(ys), max(xs), max(ys)


def _touches(a, b):
    return a[0] < b[2] and a[2] > b[0] and a[1] < b[3] and a[3] > b[1]


def make_projection(lon0, lat0, lon1, lat1, width, pad):
    """Equirectangular, x-scaled by cos(mid-latitude) so shapes stay true near the equator."""
    k = math.cos(math.radians((lat0 + lat1) / 2))
    scale = (width - 2 * pad) / ((lon1 - lon0) * k)
    height = (lat1 - lat0) * scale + 2 * pad

    def project(lon, lat):
        return pad + (lon - lon0) * k * scale, pad + (lat1 - lat) * scale

    return project, scale, height


def to_path(geom, project, min_area=0.0, tol=0.35):
    out = []
    for poly in polys(geom):
        for ring in poly:
            pts = [project(x, y) for x, y in ring]
            keep = [pts[0]]
            for p in pts[1:]:
                if abs(p[0] - keep[-1][0]) + abs(p[1] - keep[-1][1]) > tol:
                    keep.append(p)
            if len(keep) < 4:
                continue
            area = abs(sum(keep[i][0] * keep[i - 1][1] - keep[i - 1][0] * keep[i][1]
                           for i in range(len(keep)))) / 2
            if area < min_area:
                continue
            out.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in keep) + "Z")
    return "".join(out)


def main():
    adm0, adm1, lakes = (load(l) for l in LAYERS)
    uganda = next(f for f in adm0["features"] if f["properties"].get("ADMIN") == "Uganda")
    districts = [f for f in adm1["features"] if f["properties"].get("admin") == "Uganda"]
    lon0, lat0, lon1, lat1 = bbox(uganda["geometry"])
    lakes = [f for f in lakes["features"]
             if f["properties"].get("name") in LAKES and _touches(bbox(f["geometry"]),
                                                                 (lon0 - 1, lat0 - 1, lon1 + 1, lat1 + 1))]
    project, scale, height = make_projection(lon0, lat0, lon1, lat1, NAT_W, NAT_PAD)

    ilon0, ilat0, ilon1, ilat1 = INSET_BOX
    iproject, iscale, iheight = make_projection(ilon0, ilat0, ilon1, ilat1, INSET_W, 0.0)

    def overlaps_inset(geom):
        x0, y0, x1, y1 = bbox(geom)
        return x0 < ilon1 and x1 > ilon0 and y0 < ilat1 and y1 > ilat0

    data = {
        "note": "Generated by tools/fetch_geo.py from Natural Earth 10m vectors.",
        "national": {
            "width": NAT_W,
            "height": round(height, 1),
            "bbox": [lon0, lat0, lon1, lat1],
            "ptPerDeg": round(scale, 4),
            "kmPerPt": round(111.32 / scale, 5),
            "country": to_path(uganda["geometry"], project, min_area=1.0),
            "districts": to_path({"type": "MultiPolygon",
                                  "coordinates": [p for f in districts for p in polys(f["geometry"])]},
                                 project, min_area=1.0),
            "lakes": [{"name": f["properties"]["name"], "d": to_path(f["geometry"], project, min_area=2.0)}
                      for f in lakes],
        },
        "inset": {
            "width": INSET_W,
            "height": round(iheight, 1),
            "bbox": list(INSET_BOX),
            "ptPerDeg": round(iscale, 4),
            "kmPerPt": round(111.32 / iscale, 5),
            "country": to_path(uganda["geometry"], iproject, min_area=4.0, tol=0.6),
            "districts": to_path({"type": "MultiPolygon",
                                  "coordinates": [p for f in districts if overlaps_inset(f["geometry"])
                                                  for p in polys(f["geometry"])]},
                                 iproject, min_area=4.0, tol=0.6),
            "lakes": [{"name": f["properties"]["name"], "d": to_path(f["geometry"], iproject, min_area=4.0, tol=0.6)}
                      for f in lakes if overlaps_inset(f["geometry"])],
        },
    }
    data["national"]["lakes"] = [l for l in data["national"]["lakes"] if l["d"]]
    data["inset"]["lakes"] = [l for l in data["inset"]["lakes"] if l["d"]]

    out = os.path.join(ROOT, "data", "uganda-geo.json")
    with open(out, "w") as fh:
        json.dump(data, fh)
    print(f"wrote {out} ({os.path.getsize(out) / 1024:.0f} KB)")
    print(f"national {NAT_W:.0f}x{height:.0f}pt, {data['national']['kmPerPt']:.3f} km/pt")
    print(f"inset    {INSET_W:.0f}x{iheight:.0f}pt, {data['inset']['kmPerPt']:.3f} km/pt, "
          f"lakes {[l['name'] for l in data['inset']['lakes']]}")


if __name__ == "__main__":
    main()
